### ISSUE TITLE
Getting different results

### ISSUE THREAD

**Issue by suhasghorp** [bakera1/CreditDefaultSwapPricer#5]
I am looking at the TestCDSPricer-Metlife.py "testBuyProtection" results and I am not matching.
I am not using python interface, I am directly calling isda.cpp like below.
<pre>
vector < vector<double>> results;
vector<double> swaprates = { 0.01896900000000, 0.02035500000000, 0.02347700000000, 0.02481900000000, 0.02481900000000
, 0.02717200000000, 0.02654500000000, 0.02740500000000, 0.02785000000000
, 0.02802000000000, 0.02818000000000, 0.02829000000000, 0.02845500000000
, 0.02858500000000, 0.02868000000000 };
vector<string> swaptenors = { "1M", "2M", "3M", "6M", "9M", "1Y", "2Y", "3Y", "4Y", "5Y", "6Y", "7Y", "8Y", "9Y", "10Y" };
vector<double> creditspreads = { 0.00081, 0.0009, 0.00181, 0.00293, 0.00439, 0.00613, 0.00923, 0.01119 };
vector<string> credit_spread_tenors = { "6M", "1Y", "2Y", "3Y", "4Y", "5Y", "7Y", "10Y" };
vector<string> spread_roll_tenors = { "1D", "-1D", "-1W", "-1M", "-6M", "-1Y", "-5Y" };
vector<double> scenario_shifts = { -50.0, -10.0, 0.0, 10.0, 20.0, 50.0, 150.0, 100.0 };
vector<string> imm_dates = { "20/12/2018", "20/06/2019", "20/06/2020", "20/06/2021", "20/06/2022", "20/06/2023", "20/06/2025", "20/06/2028" };
results = cds_all_in_one_exclude_ir_tenor_dates(
		"13/09/2017",
		"14/09/2017",
		"20/12/2022",
		"13/04/2018",
		"20/06/2014",
		0.4,
		100.0,
		2.0,
		1, # true
		swaprates,
		swaptenors,
		creditspreads,
		credit_spread_tenors,
		spread_roll_tenors,
		imm_dates,
		scenario_shifts,
		0
	);
</pre>
And here are the results I am getting:
</pre>
pv dirty:-0.0422215
pv clean:-0.0408326
ai:0.00138889
cs01:0.000894999
dv01:9.59352e-06
</pre>
Is it possible for you to run the test again and confirm your dirty pv as -1.23099324435 ?
Thanks ,
Suhas

**Comment by bakera1** [comment]
Have a quick look; the notional here looks different to the python example.

**Comment by suhasghorp** [comment]
The notional is 2.0 in the py file, here is the relevant section :
<pre>
# economics of trade
        self.recovery_rate = 0.40000
        self.coupon = 100.0
        self.trade_date = '13/9/2017'
        self.effective_date = '14/9/2017'
        self.accrual_start_date = '20/6/2014'
        self.maturity_date = '20/12/2022'
        self.notional = 2.0 
        self.is_buy_protection = 0  # only ever buy or sell protection!
        self.verbose = 0
</pre>

Thanks.

**Comment by bakera1** [comment]
Hi,

The notional in the example test was incorrect; I have corrected this and uploaded to the new file location. All tests now reside under isda\tests so that they are deployed. The root tests directly has been removed. This highlighted a bug in the interest rate routine called which has also been fixed. For this reason since the previous versions were  hanging when called, I have uploaded a new pypi version 1.0.6 which is pinned to the github branch 1.0.6

Regards

Alex

https://github.com/bakera1/CreditDefaultSwapPricer/blob/master/isda/tests/TestCdsPricer-Metlife.py

C:\github\CreditDefaultSwapPricer\isda\tests>python TestCdsPricer-Metlife.py
cob_date: 13/04/2018 pv_dirty: 0.04222146729753646 pv_clean: 0.040832578408647575 ai: 0.001388888888888884 cs01: -894.9987755496533 dv01: -9.59351861563179 wall_time: 23.0
.
----------------------------------------------------------------------
Ran 1 test in 0.025s

OK

https://pypi.org/project/isda/#files

C:\github\CreditDefaultSwapPricer>twine upload --repository pypi --skip-existing dist/* --verbose
Enter your password:
Uploading distributions to https://upload.pypi.org/legacy/
  Skipping isda-1.0.5-cp35-cp35m-win_amd64.whl because it appears to already exist
  Skipping isda-1.0.5-cp36-cp36m-win_amd64.whl because it appears to already exist
  Skipping isda-1.0.5-cp37-cp37m-win_amd64.whl because it appears to already exist
Uploading isda-1.0.6-cp37-cp37m-win_amd64.whl
100%|████████████████████████████████████████████████████████████████████████████████████| 553k/553k [00:08<00:00, 69.7kB/s]
  Skipping isda-1.0.5.win-amd64.zip because it appears to already exist
Uploading isda-1.0.6.win-amd64.zip
100%|█████████████████████████████████████████████████████████████████████████████████████| 590k/590k [00:00<00:00, 132kB/s]

C:\github\CreditDefaultSwapPricer>

**Comment by suhasghorp** [comment]
Its correct now. Just a small observation, test_buy_protection is passing in 0 for is_buy_protection which translates to false, so test_buy_protection is actually testing sell_protection. Thanks

**Comment by bakera1** [comment]
Hi,

Perhaps you might want to change the name of the test and commit?

Regards

Alex

**Comment by suhasghorp** [comment]
Apologies for delayed response. I am not comfortable in committing the change, as I do not use git and am afraid I might screw it up. I just wanted to point out the issue, no big deal.
Another enhancement you might want to consider is, have Upfront Charge as part of the "cds all in one" results metrics. The upfront is probably the most important output of the isda model. 
Thanks.
